# Generated by Django 3.1.4 on 2020-12-03 14:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='posts.postcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='This is a test heading', max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/post/')),
                ('status', models.CharField(default='pending review', max_length=255)),
                ('visibility', models.CharField(default='public', max_length=255)),
                ('notify', models.BooleanField(default=True)),
                ('agree', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('category_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postcategory')),
                ('sub_category_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postsubcategory')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
