# Generated by Django 3.1.4 on 2020-12-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201207_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcategory', to='posts.postcategory'),
        ),
    ]
