# Generated by Django 3.1.4 on 2020-12-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201207_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='agree',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='notify',
            field=models.BooleanField(blank=True),
        ),
    ]
