# Generated by Django 3.1.4 on 2020-12-08 08:32

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201207_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='agree',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=4000, null=True, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(45)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='notify',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=75, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=75, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
