# Generated by Django 3.1.4 on 2020-12-23 14:06

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201220_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images/', validators=[posts.models.validate_post_image]),
        ),
    ]
