# Generated by Django 3.1.4 on 2020-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201208_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='images/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('africa', 'Africa'), ('antarctica', 'Antarctica'), ('asia', 'Asia'), ('australia', 'Australia'), ('europe', 'Europe'), ('north-america', 'North-America'), ('south-america', 'South-America')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending activation', 'Pending Activation'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending email verification', max_length=64),
        ),
    ]
