# Generated by Django 3.1.4 on 2020-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20201212_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='last name'),
        ),
    ]
