# Generated by Django 3.1.4 on 2022-12-31 21:49

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20201223_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_cover/', validators=[members.models.validate_profile_cover]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic/', validators=[members.models.validate_profile_image]),
        ),
    ]
